#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx ufw
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /usr/share/nginx/html/index.html
service nginx start
curl http://localhost:80/
