#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update
sudo apt-get install nginx -y

sudo bash -c "cat > /etc/nginx/conf.d/default.conf" <<EOF
server {
	listen 80;
	server_name localhost;
	root /var/www/html;

	location / {
		index index.html;
	}
}
EOF

sudo service nginx restart
curl http://localhost:80/
