#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Configure Nginx
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   
   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}" | sudo tee /etc/nginx/sites-available/default.conf

# Remove default configuration file
sudo rm /etc/nginx/sites-enabled/default

# Link new configuration and restart Nginx
sudo ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/
sudo systemctl restart nginx

